#spring:
#  datasource:
#    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#    url: jdbc:mysql://127.0.0.1:3306/ms_blog?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: MYSQL
#    show_sql: true
##    hibernate:
##      ddl-auto: create
spring:
  jpa:
    show-sql: true
    generate-ddl: false
  datasource:
    url: jdbc:h2:~/blogdb
    driverClassName: org.h2.Driver
