spring:
  application:
    name: embeddb
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MYSQL
    show_sql: true
    generate-ddl: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
server:
  port: 3333

management:
  context-path: /management
